"use client";

import React, { useState, useEffect, use } from "react";
import { apiClient } from "@/lib/api";

interface DashboardViewerProps {
  params: Promise<{
    url: string;
  }>;
}

interface DashboardData {
  id: string;
  clientName: string;
  uniqueUrl: string;
  clientInfo?: {
    description?: string;
    industry?: string;
    clientCount?: string;
    riskLevel?: string;
    complianceScore?: number;
  };
  keyMetrics?: {
    description?: string;
    totalRevenue?: string;
    nexusStates?: number;
    activeAlerts?: number;
    complianceRate?: string;
    lastAuditDate?: string;
  };
  statesMonitored?: string[];
  lastUpdated: string;
  organization?: {
    name: string;
    slug: string;
  };
}

export default function DashboardViewer({ params }: DashboardViewerProps) {
  const resolvedParams = use(params);
  const [dashboard, setDashboard] = useState<DashboardData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchDashboard = async () => {
      try {
        setLoading(true);
        const response = await apiClient.getDashboard(resolvedParams.url);
        
        if (response.success && response.data) {
          setDashboard(response.data);
        } else {
          setError(response.error || 'Failed to load dashboard');
        }
      } catch (err) {
        setError(err instanceof Error ? err.message : 'Unknown error occurred');
      } finally {
        setLoading(false);
      }
    };

    fetchDashboard();
  }, [resolvedParams.url]);

  if (loading) {
    return (
      <div className="min-h-screen bg-black flex items-center justify-center">
        <div className="text-white text-xl">Loading dashboard...</div>
      </div>
    );
  }

  if (error || !dashboard) {
    return (
      <div className="min-h-screen bg-black flex items-center justify-center">
        <div className="text-center">
          <div className="text-red-500 text-xl mb-4">Error</div>
          <div className="text-white/70">{error || 'Dashboard not found'}</div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-black">
      {/* Header */}
      <div className="bg-white/5 backdrop-blur-xl border-b border-white/10">
        <div className="max-w-7xl mx-auto px-6 py-6">
          <div className="flex items-center justify-between">
            <div>
              <h1 className="text-3xl font-semibold text-white mb-2" style={{ fontFamily: 'Helvetica, Arial, sans-serif' }}>
                {dashboard.clientName} Dashboard
              </h1>
              <p className="text-white/60" style={{ fontFamily: 'Helvetica, Arial, sans-serif' }}>
                Generated by {dashboard.organization?.name || 'Demo Organization'}
              </p>
            </div>
            <div className="text-right">
              <div className="text-white/60 text-sm" style={{ fontFamily: 'Helvetica, Arial, sans-serif' }}>
                Last Updated
              </div>
              <div className="text-white" style={{ fontFamily: 'Helvetica, Arial, sans-serif' }}>
                {new Date(dashboard.lastUpdated).toLocaleDateString()}
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Main Content */}
      <div className="max-w-7xl mx-auto px-6 py-8">
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          
          {/* Client Information */}
          <div className="lg:col-span-1">
            <div className="bg-white/5 backdrop-blur-xl rounded-2xl border border-white/10 p-6">
              <h2 className="text-xl font-semibold text-white mb-4" style={{ fontFamily: 'Helvetica, Arial, sans-serif' }}>
                Client Information
              </h2>
              <div className="space-y-4">
                <div>
                  <div className="text-white/60 text-sm mb-1" style={{ fontFamily: 'Helvetica, Arial, sans-serif' }}>
                    Description
                  </div>
                  <div className="text-white" style={{ fontFamily: 'Helvetica, Arial, sans-serif' }}>
                    {dashboard.clientInfo?.description || 'Multi-state client dashboard with comprehensive tax monitoring'}
                  </div>
                </div>
                <div>
                  <div className="text-white/60 text-sm mb-1" style={{ fontFamily: 'Helvetica, Arial, sans-serif' }}>
                    Industry
                  </div>
                  <div className="text-white" style={{ fontFamily: 'Helvetica, Arial, sans-serif' }}>
                    {dashboard.clientInfo?.industry || 'Professional Services'}
                  </div>
                </div>
                <div>
                  <div className="text-white/60 text-sm mb-1" style={{ fontFamily: 'Helvetica, Arial, sans-serif' }}>
                    Client Count
                  </div>
                  <div className="text-white" style={{ fontFamily: 'Helvetica, Arial, sans-serif' }}>
                    {dashboard.clientInfo?.clientCount || '50-100 clients'}
                  </div>
                </div>
                <div>
                  <div className="text-white/60 text-sm mb-1" style={{ fontFamily: 'Helvetica, Arial, sans-serif' }}>
                    Risk Level
                  </div>
                  <div className={`px-3 py-1 rounded-full text-xs font-medium ${
                    dashboard.clientInfo?.riskLevel === 'low' ? 'bg-green-600 text-white' :
                    dashboard.clientInfo?.riskLevel === 'medium' ? 'bg-yellow-600 text-white' :
                    'bg-red-600 text-white'
                  }`} style={{ fontFamily: 'Helvetica, Arial, sans-serif' }}>
                    {(dashboard.clientInfo?.riskLevel || 'medium').toUpperCase()}
                  </div>
                </div>
                <div>
                  <div className="text-white/60 text-sm mb-1" style={{ fontFamily: 'Helvetica, Arial, sans-serif' }}>
                    Compliance Score
                  </div>
                  <div className="text-white text-2xl font-semibold" style={{ fontFamily: 'Helvetica, Arial, sans-serif' }}>
                    {dashboard.clientInfo?.complianceScore || 85}%
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Key Metrics */}
          <div className="lg:col-span-2">
            <div className="bg-white/5 backdrop-blur-xl rounded-2xl border border-white/10 p-6">
              <h2 className="text-xl font-semibold text-white mb-4" style={{ fontFamily: 'Helvetica, Arial, sans-serif' }}>
                Key Metrics
              </h2>
              <div className="mb-4">
                <div className="text-white/60 text-sm mb-1" style={{ fontFamily: 'Helvetica, Arial, sans-serif' }}>
                  Description
                </div>
                <div className="text-white" style={{ fontFamily: 'Helvetica, Arial, sans-serif' }}>
                  {dashboard.keyMetrics?.description || 'Real-time compliance tracking and threshold monitoring'}
                </div>
              </div>
              
              <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
                <div className="text-center">
                  <div className="text-white/60 text-sm mb-1" style={{ fontFamily: 'Helvetica, Arial, sans-serif' }}>
                    Total Revenue
                  </div>
                  <div className="text-white text-xl font-semibold" style={{ fontFamily: 'Helvetica, Arial, sans-serif' }}>
                    {dashboard.keyMetrics?.totalRevenue || '$2.5M'}
                  </div>
                </div>
                <div className="text-center">
                  <div className="text-white/60 text-sm mb-1" style={{ fontFamily: 'Helvetica, Arial, sans-serif' }}>
                    Nexus States
                  </div>
                  <div className="text-white text-xl font-semibold" style={{ fontFamily: 'Helvetica, Arial, sans-serif' }}>
                    {dashboard.keyMetrics?.nexusStates || 10}
                  </div>
                </div>
                <div className="text-center">
                  <div className="text-white/60 text-sm mb-1" style={{ fontFamily: 'Helvetica, Arial, sans-serif' }}>
                    Active Alerts
                  </div>
                  <div className="text-white text-xl font-semibold" style={{ fontFamily: 'Helvetica, Arial, sans-serif' }}>
                    {dashboard.keyMetrics?.activeAlerts || 3}
                  </div>
                </div>
                <div className="text-center">
                  <div className="text-white/60 text-sm mb-1" style={{ fontFamily: 'Helvetica, Arial, sans-serif' }}>
                    Compliance Rate
                  </div>
                  <div className="text-white text-xl font-semibold" style={{ fontFamily: 'Helvetica, Arial, sans-serif' }}>
                    {dashboard.keyMetrics?.complianceRate || 92}%
                  </div>
                </div>
              </div>
              
              <div className="mt-6">
                <div className="text-white/60 text-sm mb-1" style={{ fontFamily: 'Helvetica, Arial, sans-serif' }}>
                  Last Audit Date
                </div>
                <div className="text-white" style={{ fontFamily: 'Helvetica, Arial, sans-serif' }}>
                  {dashboard.keyMetrics?.lastAuditDate ? new Date(dashboard.keyMetrics.lastAuditDate).toLocaleDateString() : '1/12/2024'}
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* States Monitored */}
        <div className="mt-8">
          <div className="bg-white/5 backdrop-blur-xl rounded-2xl border border-white/10 p-6">
            <h2 className="text-xl font-semibold text-white mb-4" style={{ fontFamily: 'Helvetica, Arial, sans-serif' }}>
              States Monitored
            </h2>
            <div className="flex flex-wrap gap-3">
              {(dashboard.statesMonitored || ['CA', 'TX', 'NY', 'FL', 'IL', 'PA', 'OH', 'GA', 'NC', 'MI']).map((state, index) => (
                <div
                  key={index}
                  className="px-4 py-2 bg-blue-600 text-white rounded-full text-sm font-medium"
                  style={{ fontFamily: 'Helvetica, Arial, sans-serif' }}
                >
                  {state}
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
